import React from 'react'
import { Container } from 'react-bootstrap'
import { ServicesHero } from '../../components/ServicesHero'
import { ServicesSection } from "../../components/ServicesSection.jsx";
import { WhyChooseUs } from "../../components/WhyChooseUs.jsx";
import { Works } from "../../components/Works.jsx";

export const metadata = {
    title: "Ride With Us",
    description: "Generated by create next app",
};
const Ride = () => {
    return (
        <>
            <ServicesHero
                subtitle="Upto 25%"
                title="off on first booking through our App"
                description="Sagittis Nunc Orci Posuere Eget Adipiscing Quisque. Vitae Commodo Urna Vitae Placerat."
            />
            <ServicesSection />
            <WhyChooseUs />
            <Works />

        </>
    )
}

export default Ride
