import 'bootstrap/dist/css/bootstrap.min.css';
import { Outfit } from "next/font/google";
import { Header } from './components/Header';
import Footer from "./components/Footer";
import "./globals.css";
import "./responsive.css";

export const metadata = {
  title: "Kings Ride",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={outfit.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
