import React from 'react'

export const metadata = {
  title: "About us",
  description: "Generated by create next app",
};
const About = () => {
  return (
    <>

      <div>page</div>
    </>
  )
}

export default About